/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package metronomocontador;


import com.jd.swing.custom.component.button.CircularGlossyButton;
import static com.jd.swing.demo.button.CircularGlossyButtonDemo.getButtonsPanel;
import com.jd.swing.demo.button.GlossyButtonDemo;
import com.jd.swing.util.Theme;
import java.awt.Color;
import java.awt.Desktop;  
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.net.URI;  
import java.io.IOException;
import java.net.URISyntaxException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonas
 */
public class frmMetronomo extends javax.swing.JFrame {

    metronomo metro;
    int rodando = 0;
    /**
     * Creates new form frmMetronomo
     */
    public frmMetronomo() {
        initComponents();
        
        CircularGlossyButton lightGreen = new CircularGlossyButton("Button",
				Theme.GLOSSY_LIGHTGREEN_THEME);
		lightGreen.setPreferredSize(new Dimension(75, 75));
        
        getContentPane().add(lightGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 133, -1, -1));
        
        GlossyButtonDemo demo= new GlossyButtonDemo();
		JFrame frame = new JFrame("Custom Buttons Demo");
		//frame.setLayout(new FlowLayout());

		frame.add(demo.getButtonsPanel());
		// frame.getContentPane().setBackground(Color.BLACK);
		frame.setBackground(Color.BLACK);
		frame.setSize(700, 85);
		frame.setVisible(true);
                
                JFrame frame1 = new JFrame("Custom Buttons Demo");
		frame1.setLayout(new FlowLayout());
		CircularGlossyButton standardButton = new CircularGlossyButton(
				"Standard Button");
		getButtonsPanel(frame1);                
		frame1.getContentPane().setBackground(Color.WHITE);
		frame1.setBackground(Color.WHITE);
		frame1.setSize(700, 85);
		frame1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRDB = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        slideVelo = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        lblVelocidade = new javax.swing.JLabel();
        rdbSelecionar = new javax.swing.JRadioButton();
        rdbEspecificar = new javax.swing.JRadioButton();
        txtVelocidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboTempos = new javax.swing.JComboBox();
        cboNota = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        btnParar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtQuantidadeExercicio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCompassosExercicio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtExerciciosRealizados = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metronomo Contador");
        setBackground(new java.awt.Color(204, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 51, 51));
        setMaximumSize(new java.awt.Dimension(304, 378));
        setMinimumSize(new java.awt.Dimension(304, 378));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setText("Metrônomo Contador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        slideVelo.setMaximum(210);
        slideVelo.setMinimum(35);
        slideVelo.setValue(90);
        slideVelo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slideVeloStateChanged(evt);
            }
        });
        getContentPane().add(slideVelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 101, 142, -1));
        slideVelo.getAccessibleContext().setAccessibleName("slideVelo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Velocidade / Andamento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("BPM");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 133, -1, -1));

        btnIniciar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 336, -1, -1));
        btnIniciar.getAccessibleContext().setAccessibleName("btnIniciar");

        lblVelocidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVelocidade.setText("90");
        getContentPane().add(lblVelocidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 133, -1, -1));
        lblVelocidade.getAccessibleContext().setAccessibleName("lblVelocidade");

        grupoRDB.add(rdbSelecionar);
        rdbSelecionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbSelecionar.setSelected(true);
        rdbSelecionar.setText("Selecionar");
        getContentPane().add(rdbSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));
        rdbSelecionar.getAccessibleContext().setAccessibleName("rdbSelecionar");
        rdbSelecionar.getAccessibleContext().setAccessibleDescription("");

        grupoRDB.add(rdbEspecificar);
        rdbEspecificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbEspecificar.setText("Especificar");
        getContentPane().add(rdbEspecificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 168, -1, -1));
        rdbEspecificar.getAccessibleContext().setAccessibleName("rdbEspecificar");

        txtVelocidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtVelocidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 169, 78, -1));
        txtVelocidade.getAccessibleContext().setAccessibleName("txtVelocidade");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("BPM");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 172, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Compasso");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 214, -1, -1));

        cboTempos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboTempos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4", "2", "3", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cboTempos.setToolTipText("");
        getContentPane().add(cboTempos, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 211, 46, -1));
        cboTempos.getAccessibleContext().setAccessibleName("cboTempos");

        cboNota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboNota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4", "1", "2", "8", "16", "32", "64" }));
        getContentPane().add(cboNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 46, -1));
        cboNota.getAccessibleContext().setAccessibleName("cboNota");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Por");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 214, -1, -1));

        btnParar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnParar.setText("Parar");
        btnParar.setToolTipText("");
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });
        getContentPane().add(btnParar, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 340, -1, -1));
        btnParar.getAccessibleContext().setAccessibleName("btnParar");

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setToolTipText("");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 340, -1, -1));
        btnSair.getAccessibleContext().setAccessibleName("btnSair");

        txtQuantidadeExercicio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtQuantidadeExercicio.setText("20");
        getContentPane().add(txtQuantidadeExercicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 245, 31, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Quantidade Exercicios");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 245, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Compassos por Exercicio");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 267, -1, -1));

        txtCompassosExercicio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCompassosExercicio.setText("2");
        getContentPane().add(txtCompassosExercicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 267, 31, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Exercicios Realizados");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 298, -1, -1));

        txtExerciciosRealizados.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtExerciciosRealizados.setText("0");
        getContentPane().add(txtExerciciosRealizados, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 298, 31, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slideVeloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slideVeloStateChanged
        // atualizando lblvelocidade
        lblVelocidade.setText(Integer.toString(slideVelo.getValue()));
    }//GEN-LAST:event_slideVeloStateChanged

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed

        
        
//parte principal
        int bpm;
        int nota;
        int tempos;
        
        if (rdbSelecionar.isSelected()) {
            bpm = slideVelo.getValue();
        }
        else {
            bpm = Integer.parseInt(txtVelocidade.getText());
        }
        
        tempos = Integer.parseInt( (String) cboTempos.getSelectedItem());
        nota = Integer.parseInt( (String) cboNota.getSelectedItem());
        
        if (rodando == 1) {
            metro.encerrar();
        }
        
        int quanidadeExercicios = Integer.parseInt(txtQuantidadeExercicio.getText());
        int compassosPorExercicio = Integer.parseInt(txtCompassosExercicio.getText());
        
        txtExerciciosRealizados.setText("0");
        
        metro = new metronomo(bpm, tempos,nota,quanidadeExercicios,compassosPorExercicio,txtExerciciosRealizados);
        metro.run();
        rodando = 1;
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        // TODO add your handling code here:
         metro.encerrar();
         rodando = 0;
    }//GEN-LAST:event_btnPararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMetronomo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMetronomo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMetronomo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMetronomo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmMetronomo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox cboNota;
    private javax.swing.JComboBox cboTempos;
    private javax.swing.ButtonGroup grupoRDB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblVelocidade;
    private javax.swing.JRadioButton rdbEspecificar;
    private javax.swing.JRadioButton rdbSelecionar;
    private javax.swing.JSlider slideVelo;
    private javax.swing.JTextField txtCompassosExercicio;
    private javax.swing.JTextField txtExerciciosRealizados;
    private javax.swing.JTextField txtQuantidadeExercicio;
    private javax.swing.JTextField txtVelocidade;
    // End of variables declaration//GEN-END:variables
}


